name: onclickproperty
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.11.0
  http: ^0.13.2
  flutter_swiper: ^1.1.6
  carousel_slider: ^2.3.1
  photo_view: ^0.10.3
  multi_select_flutter: ^3.1.6
  dropdown_search: ^0.4.6
  datetime_picker_formfield: ^1.0.0
  intl: ^0.17.0
  dio: ^4.0.0
  introduction_screen: ^1.0.7
#  google_fonts: ^1.1.2
#  image_form_field: ^0.1.0
#  cool_alert: ^1.0.3
  cool_stepper: ^1.1.3
  http_parser: ^4.0.0
  mime: ^0.9.7
  path: ^1.7.0
  file_picker: ^3.0.1
#  image_picker: ^0.6.7+4
  image_picker: ^0.7.4
#  shared_preferences: ^0.5.8
  shared_preferences: ^2.0.5
#  firebase_core: ^0.5.0
  firebase_core: ^1.0.0
#  firebase_auth: ^0.18.0+1
  firebase_auth: ^1.1.0
  google_sign_in: ^4.5.3
  fluttertoast: ^7.1.1
  uuid: ^3.0.4
  geocoder: ^0.2.1
  flutter_svg: ^0.22.0
  provider: ^4.3.1
  flutter_facebook_login: ^3.0.0
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  razorpay_flutter: ^1.2.5
#  url_launcher: ^5.7.10
  flutter_launcher_icons: ^0.9.0
  payu_money_flutter: ^0.0.3
  firebase_messaging: ^9.0.0
  url_launcher: ^6.0.2
  need_resume: ^1.0.6
#  flutter_login_facebook: ^0.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
